### ISSUE TITLE
Cartridge support for VFX/VFX-SD keyboards

### ISSUE THREAD

**Issue by sysfu** [JamesHagerman/Ensoniq-ESQ-1-EEPROM-Cartridge#1]
Have you tried using this cartridge on the VFX/VFX-SD keyboards?

Used cartridges for these keyboards are very expensive as well and I was hoping I could use this project instead.

**Comment by JamesHagerman** [comment]
Sorry for the delayed reply!

I did consider this but it ended up being too large of a lift given the relative lack of documentation for the VFX when compared to the ESQ-1.

The VFX/VFX-SD keyboards use an entirely different pinout and memory storage system. There are a LOT more parameters to store on a VFX than the ESQ-1/SQ-80 so the cartridges are more complex.
